### ISSUE TITLE
Configuring local cluster

### ISSUE THREAD

**Issue by bergur88** [drpebcak/rancher-as-code#7]
Hi, thanks for this great guide. 
I'm trying to configure the local cluster, specifically to enable cluster monitoring.
The problem i'm having is that the cluster is not in the terraform state understandably.
So i cannot do something like this (as terraform wants to create a new cluster):
```
resource "rancher2_cluster" "local" {
  name = "local"
  description = "Foo rancher2 imported cluster"
  depends_on = ["rancher2_bootstrap.admin"]
  enable_cluster_monitoring = true
}
```
I looked around RKE and the rancher helm chart and couldn't find anywhere where you could configure cluster_monitoring on the local cluster there.

I could [import](https://www.terraform.io/docs/import/index.html) the state of the local cluster to terraform manually, but i would really prefer not having a manual step.

Do you have any pointers on how this can be achived using terraform as i would like this to be automated.

**Comment by drpebcak** [comment]
You would use the `rancher2_cluster` datasource for this.

```
data "rancher2_cluster" "local" {
  name = "local"
}
```
